project:
  type: book

book:
  title: "Secondary Soft Skills"
  subtitle: "MACEPA Data Fellowship Training Program"
  chapters: 
    - index.qmd
    - request_into_analysis.qmd 
  
format:
  html:
    theme:
    - cosmo
    - custom.scss
    template-partials: title-block.html
    css: include/webex.css
    include-after-body: include/webex.js
    embed-resources: true 
  # pdf:
  #   documentclass: scrreprt
editor: visual


